import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React, { useState, useEffect } from "react";
import { io } from "socket.io-client";
// import router
var socket;
export default function Home() {
  // const [input, setInput] = useState("");
  const isSocketConnected = () => {
    return socket && socket.connected;
  };
  const socketInitializer = async () => {
    await fetch("/api/sockets");
    socket = io();

    socket.on("connect", () => {
      console.log("connected", isSocketConnected());
      console.log("connected", socket.id);
    });

    socket.on("new_message", (msg) => {
      console.log(msg);
    });
  };
  // const onChangeHandler = (e) => {
  //   setInput(e.target.value);
  //   socket.emit("get-request", e.target.value);
  // };
  useEffect(() => {
    console.log("SE EJECUTA");
    socketInitializer();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <button
          onClick={() => {
            console.log("test");
            window.location.href = "/";
          }}
        >
          PRESS ME
        </button>
      </main>
    </>
  );
}
